<a href="https://colab.research.google.com/github/taeuk91/Tensorflow2/blob/main/TF_class_2_Variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
# input 배열의 각 원소를 x Tensor의 배열에 곱한 후, 각 원소에 5씩 더한다
input = [1, 2, 3, 4, 5]

In [ ]:
x = tf.Variable(tf.ones(shape=(5)), name="x")

# tensorflow version 1에서는 placeholder를 사용
# x = tf.placeholder(dtype=tf.float32)
# y = x + 5
# sess = tf.Session()
# sess.run(y, feed_dict={x: input})

def add_function(x):
  return x + 5

In [ ]:
y = input * x
print(y)

# 

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [ ]:
add_function(y)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 6.,  7.,  8.,  9., 10.], dtype=float32)>

In [ ]:
# 수학 성적과 영어 성적의 평균값 구하기

mathScore = [80, 99, 84, 97, 92]
englishScore = [80, 80, 84, 68, 77]

a = tf.Variable(tf.ones(shape=(5)), name="a") # 그릇 a
b = tf.Variable(tf.ones(shape=(5)), name="b") # 그릇 b

def average_function(a, b): 
  return (a + b) / 2

In [ ]:
c = mathScore * a
d = englishScore * b

t = average_function(c, d)
print(t)
t.numpy()

tf.Tensor([80.  89.5 84.  82.5 84.5], shape=(5,), dtype=float32)


array([80. , 89.5, 84. , 82.5, 84.5], dtype=float32)